`timescale 1ns/1ps

module tb_up_down_counter;

    reg clk;
    reg reset;
    reg up_down;
    wire [3:0] count;

    up_down_counter uut (
        .clk(clk),
        .reset(reset),
        .up_down(up_down),
        .count(count)
    );

    // Clock generation
    always #5 clk = ~clk;

    initial begin
        $monitor("Time=%0t | Reset=%b | Up_Down=%b | Count=%d",
                 $time, reset, up_down, count);

        clk = 0;
        reset = 1;
        up_down = 1;

        #10;
        reset = 0;

        // Up counting
        up_down = 1;
        #80;

        // Down counting
        up_down = 0;
        #80;

        $finish;
    end

endmodule